[project]
name = 'Tokenized-Infrastructure-Maintenance-Funding'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-registration]
path = 'contracts/asset-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.condition-assesment]
path = 'contracts/condition-assesment.clar'
clarity_version = 2
epoch = 2.5

[contracts.contractor-management]
path = 'contracts/contractor-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.fund-allocation]
path = 'contracts/fund-allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
